spring:
  application:
    name: product-management-service
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate_db
    username: root
    password: Priyo123
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8361

logging:
  level:
    root: info
